# Chunk properties
chunk:
  size: 500
  overlap: 100

# Vector database properties
vector:
  db: chroma
  collection: documents

# LLM properties
llm:
  provider: ollama
  host: http://localhost:11434
  model: sam860/LFM2:350m
